### PR TITLE
Support for Scala 2.13

### PR DESCRIPTION
**Pull request by kammoh**
Add support for Scala 2.13.

- Remove deprecated `TestAdapters.ReadyValidSource` and `TestAdapters.ReadyValidSink`
- Use explicit version for `utest`

### CODE REVIEW

**Review by ekiwi — CHANGES_REQUESTED** [review]
This looks great!
The one thing missing is to add Scala 2.13.5 to the CI: https://github.com/ucb-bar/chisel-testers2/blob/master/.github/workflows/test.yml#L16

**Comment by ekiwi** [comment]
The CI failure might be cause by an upstream chisel change that I recently made, don't worry about it for now.

**Review by ducky64 — APPROVED** [review]
Code changes look fine, and adding to CI would be useful.

**Comment by ekiwi** [comment]
> The CI failure might be cause by an upstream chisel change that I recently made, don't worry about it for now.

@kammoh Once you rebase on the latest `master` the CI failures should go away.

**Comment by kammoh** [comment]
I somehow messed up the rebase and had to force push 😬  Is it still alright despite that?
The CI doesn't seem to be triggered, probably due to pending change requests which I can't access now

**Review by ekiwi — APPROVED** [review]
:ship:

**Pull request merged**
