### PR TITLE
Simplify CI

### PR DESCRIPTION
**Pull request by jackkoenig**

### CODE REVIEW

**Comment by jackkoenig** [comment]
It's not clear if caching will work when running inside of the chisel-tools Docker container so this should be fun.

**Comment by jackkoenig** [comment]
Okay so this "works" but caching doesn't yet

**Review by chick — APPROVED** [review]
lgtm

**Comment by jackkoenig** [comment]
This currently does not cache downloaded dependencies, but it's fast enough that it isn't a huge problem. Future work is to make caching work properly.

**Comment by jackkoenig** [comment]
@Mergifyio backport 0.3.x

**Pull request merged**
