### PR TITLE
Chisel 3.5: MultiIOModule is now just Module

### PR DESCRIPTION
**Pull request by ekiwi**
This leaves us with a single deprecation warning when compiling `chiseltest`.

### CODE REVIEW

**Comment by ducky64** [comment]
Code looks fine, but appears tests are failing because it's still picking up old Module?

**Comment by ekiwi** [comment]
> Code looks fine, but appears tests are failing because it's still picking up old Module?

I think it has something to do with Scala 2.11. Maybe we stopped publishing 2.11 snapshots of Chisel/firrtl? @jackkoenig

**Comment by jackkoenig** [comment]
> > Code looks fine, but appears tests are failing because it's still picking up old Module?
> 
> I think it has something to do with Scala 2.11. Maybe we stopped publishing 2.11 snapshots of Chisel/firrtl? @jackkoenig

We did for Chisel master yeah, so we need to drop it here.

**Comment by ekiwi** [comment]
Now it passes :tada:

**Review by ducky64 — APPROVED** [review]

**Pull request merged**
