### PR TITLE
DependencyAPI Phase 2

### PR DESCRIPTION
**Pull request by sequencer**
1. refactor stage/phase introduced in #247.
1. refacotr ThreadedBacked and BackendInterface.

Diff https://github.com/sequencer/chisel-testers2/compare/dependencyapi_phase1...sequencer:dependencyapi_phase2

### CODE REVIEW

**Review by ducky64 — CHANGES_REQUESTED** [review]
Can you change the PR target to your phase 1 PR, so the diff / files changed interface only shows the changes above your phase 1 instead of showing the combined ones?

Will review once the diff interface is clean; it's not helpful to do a review of individual parts where the diff is cumulative.

(this also applies to the other phases after this one)

**Comment by sequencer** [comment]
Sorry for the late reply, I was on the vacation these days.
Happy new year:)

> Can you change the PR target to your phase 1 PR, so the diff / files changed interface only shows the changes above your phase 1 instead of showing the combined ones?

I tried to do this, but in the main repo, I cannot PR to my a branch of my own fork. Can you add me to collaborator that I create a specific branch and PR to it.

**Comment by ducky64** [comment]
Done (I think?) - let me know if something still isn't working.

**Comment by sequencer** [comment]
#254

**Pull request closed without merging**
