### PR TITLE
Use release version of utest

### PR DESCRIPTION
**Pull request by jackkoenig**
(I haven't actually run this, assuming CI will check)

### CODE REVIEW

**Comment by ducky64** [comment]
We actually don't have CI set up for this repo...

@ucbjrl how difficult would it be to get CI integrated with PRs?

**Comment by ucbjrl** [comment]
Once we get the RC1 release out, I'll focus on adding CI to the remaining chisel repositories.

**Comment by ducky64** [comment]
Is this expected from sbt?

```
chisel-testers2: test
[info] Updating
[info] Resolved  dependencies
[warn]
[warn]  Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last update for the full output
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.lihaoyi:utest_2.12:0.6.8
[error]   Not found
[error]   Not found
[error]   not found: /home/.../.ivy2/local/com.lihaoyi/utest_2.12/0.6.8/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/lihaoyi/utest_2.12/0.6.8/utest_2.12-0.6.8.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/lihaoyi/utest_2.12/0.6.8/utest_2.12-0.6.8.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/lihaoyi/utest_2.12/0.6.8/utest_2.12-0.6.8.pom
[error] Total time: 2 s, completed Mar 26, 2020, 4:27:53 PM
```

**Comment by ucbjrl** [comment]
No. I think we need to use version 0.6.6 - it's the "current" release and I think it's the only one compatible with both Scala 2.11 and Scala 2.12.
Good catch @ducky64. I was a little quick to accept the 0.6.8 version.

**Comment by ekiwi** [comment]
Please make another PR if you still want to update.

**Pull request closed without merging**
