### PR TITLE
Only print Verilator messages in verbose mode

### LINKED ISSUE #412: Test output when using Verilator backend could be less verbose
To have a cleaner output during the tests, the following console outputs could be printed only on some kind of verbose mode:

https://github.com/ucb-bar/chisel-testers2/blob/b87732a765425c5f757f5f14053a369ab820a02d/src/main/scala/chiseltest/simulator/jna/VerilatorCppJNAHarnessGenerator.scala#L234

https://github.com/ucb-bar/chisel-testers2/blob/b87732a765425c5f757f5f14053a369ab820a02d/src/main/scala/chiseltest/simulator/VerilatorSimulator.scala#L172

Currently it is printing:

```
...
[info] - should NEQ
[info] - should GT
[info] - should GTU
Enabling waves..
Deleting stale Verilator object directory: /Users/cdepaula/repos/chiselv/test_run_dir/GPIO_should_write_IO_data_to_output/verilated
Enabling waves..
Deleting stale Verilator object directory: /Users/cdepaula/repos/chiselv/test_run_dir/CPUSingleCycleApps_should_loop_thru_ascii_table_writing_to_0x3000_0000_region/verilated
Enabling waves..
[info] GPIOSpec:
[info] GPIO
[info] - should read IO when as 0 when initialized
[info] - should write direction
[info] - should write IO data to output
...
```

### PR DESCRIPTION
**Pull request by carlosedp**
Fixes #412

### CODE REVIEW

**Comment by ekiwi** [comment]
@carlosedp I added the annotation. Could you please test all the changes together to see if it fixes the issue for you?

**Comment by carlosedp** [comment]
Just tested it and works perfectly. I just added a commit exposing the `SimulatorDebugAnnotation` annotation in the chiseltest package.

**Comment by carlosedp** [comment]
Ah ok... no probs, one can import `chiseltest.simulator.SimulatorDebugAnnotation` if needed.

**Comment by ekiwi** [comment]
> Awesome, thanks for the help Kevin!

Thanks for getting this PR going! Great work!

**Comment by carlosedp** [comment]
How long does it take to get the HEAD published as 0.5-SNAPSHOT?

**Pull request merged**
