### PR TITLE
Verilator 4 202 problems on ubuntu 20 04

### PR DESCRIPTION
**Pull request by oharboe**

### CODE REVIEW

**Comment by ekiwi** [comment]
Thanks for trying to reproduce your problem, @oharboe !

It would be great if you could rebase this on top of the latest `master` since we just merged a PR from @kammoh that fixes the OpenJDK11 issue.

@ryan-lund it would be great if you could have a look at this.

**Comment by oharboe** [comment]
verilator 4.202 still fails after rebase on master.

**Comment by kammoh** [comment]
Is this PR adding compatibility with verilator `4.202` (which is currently not supported)? I see `Text file busy` error in the CI sbt test logs, which suggests verilated model was running at the same time another test was building the same executable file, i.e. a race condition. 
Can you try disabling parallel runs? I guess adding `Test / parallelExecution := false` should do.

**Comment by oharboe** [comment]
> Is this PR adding compatibility with verilator `4.202` (which is currently not supported)?
> I see `Text file busy` error in the CI sbt test logs, which suggests verilated model was running at the same time another test was building the same executable file, i.e. a race condition.
> Can you try disabling parallel runs? I guess adding `Test / parallelExecution := false` should do.

No. I previously had to work around limitations that broke Java 11. That's no longer necessary, so I guess this should now be a github issue and not a pull request: Verilator 4.202 doesn't work on master.

**Comment by ekiwi** [comment]
> Verilator 4.202 doesn't work on master.

Oh OK. So Verilator `4.202` is currently not supported: https://github.com/ucb-bar/chisel-testers2#verilator-backend
I welcome PRs to add support, but currently I do not have time to add support myself.

**Comment by oharboe** [comment]
> > Verilator 4.202 doesn't work on master.
> 
> Oh OK. So Verilator `4.202` is currently not supported: https://github.com/ucb-bar/chisel-testers2#verilator-backend
> I welcome PRs to add support, but currently I do not have time to add support myself.

See #311 there is a problem with 4.028 as wella s 4.202, I suspect the same problem, different error messages. 

Now that master works with jdk 11, this branch has served it's purpose. Closing.

**Pull request closed without merging**
